/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VettingRouteImport } from './routes/vetting'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgoraRouteImport } from './routes/agora'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EducatorsIdRouteImport } from './routes/educators.$id'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminTeachersIdRouteImport } from './routes/admin.teachers.$id'

const VettingRoute = VettingRouteImport.update({
  id: '/vetting',
  path: '/vetting',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgoraRoute = AgoraRouteImport.update({
  id: '/agora',
  path: '/agora',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducatorsIdRoute = EducatorsIdRouteImport.update({
  id: '/educators/$id',
  path: '/educators/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersIdRoute = AdminTeachersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTeachersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agora': typeof AgoraRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/messages': typeof MessagesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/vetting': typeof VettingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/educators/$id': typeof EducatorsIdRoute
  '/admin/teachers/$id': typeof AdminTeachersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agora': typeof AgoraRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/messages': typeof MessagesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/vetting': typeof VettingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/educators/$id': typeof EducatorsIdRoute
  '/admin/teachers/$id': typeof AdminTeachersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agora': typeof AgoraRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/messages': typeof MessagesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/vetting': typeof VettingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/educators/$id': typeof EducatorsIdRoute
  '/admin/teachers/$id': typeof AdminTeachersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agora'
    | '/dashboard'
    | '/how-it-works'
    | '/messages'
    | '/sign-in'
    | '/sign-up'
    | '/vetting'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/teachers'
    | '/educators/$id'
    | '/admin/teachers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agora'
    | '/dashboard'
    | '/how-it-works'
    | '/messages'
    | '/sign-in'
    | '/sign-up'
    | '/vetting'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/teachers'
    | '/educators/$id'
    | '/admin/teachers/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agora'
    | '/dashboard'
    | '/how-it-works'
    | '/messages'
    | '/sign-in'
    | '/sign-up'
    | '/vetting'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/teachers'
    | '/educators/$id'
    | '/admin/teachers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgoraRoute: typeof AgoraRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MessagesRoute: typeof MessagesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VettingRoute: typeof VettingRoute
  EducatorsIdRoute: typeof EducatorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vetting': {
      id: '/vetting'
      path: '/vetting'
      fullPath: '/vetting'
      preLoaderRoute: typeof VettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agora': {
      id: '/agora'
      path: '/agora'
      fullPath: '/agora'
      preLoaderRoute: typeof AgoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educators/$id': {
      id: '/educators/$id'
      path: '/educators/$id'
      fullPath: '/educators/$id'
      preLoaderRoute: typeof EducatorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers/$id': {
      id: '/admin/teachers/$id'
      path: '/$id'
      fullPath: '/admin/teachers/$id'
      preLoaderRoute: typeof AdminTeachersIdRouteImport
      parentRoute: typeof AdminTeachersRoute
    }
  }
}

interface AdminTeachersRouteChildren {
  AdminTeachersIdRoute: typeof AdminTeachersIdRoute
}

const AdminTeachersRouteChildren: AdminTeachersRouteChildren = {
  AdminTeachersIdRoute: AdminTeachersIdRoute,
}

const AdminTeachersRouteWithChildren = AdminTeachersRoute._addFileChildren(
  AdminTeachersRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeachersRoute: typeof AdminTeachersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeachersRoute: AdminTeachersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgoraRoute: AgoraRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  MessagesRoute: MessagesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VettingRoute: VettingRoute,
  EducatorsIdRoute: EducatorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
